name: vampire
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - biopython
  - pandas
  - parallel
  - pip
  - pydot
  - pytest
  - scikit-learn
  - scons
  - yapf
  - pip:
    - black
    - click
    - docformatter
    - exrex
    - flake8
    - nestly
    - tensorflow
    - versioneer
